# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM python:3.11-slim
WORKDIR /app
# Install dependencies
COPY pyproject.toml requirements.txt ./
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir .
# Copy source code
COPY mcp_server_servicenow ./mcp_server_servicenow
# Expose no port since stdio
ENTRYPOINT ["python", "-m", "mcp_server_servicenow.cli"]
